name: CI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Переконайся, що папка називається саме services/catalog-service
      - name: Install dependencies
        run: npm install
        working-directory: ./services/catalog-service

      #- name: Run tests
        working-directory: ./services/catalog-service
        run: |
          chmod +x ./node_modules/.bin/jest
          npm test --if-present
        
      - name: Build Docker Image (Check)
        uses: docker/build-push-action@v5
        with:
          context: ./services/catalog-service
          push: false 
          tags: catalog-service:test